Timecode struct update for Milliseconds
media-io/timecode pull request #7
Opened 2023-10-03 10:12 UTC by Damien-Renault

2023-10-03 12:11 UTC, VincentJousse commented on src/lib.rs
> +    let seconds = duration.as_secs() - hours * 3600 - minutes * 60;
```suggestion
    let remaining = duration.as_secs();
    let hours = remaining / 3600;
    let remaining %= 3600;
    let minutes = remaining / 60;
    let seconds = remaining % 60;
```

2023-10-03 12:11 UTC, VincentJousse commented on src/lib.rs
>    fn from((frames, video_frame_rate): (u32, FrameRate)) -> Self {
Rename video_frame_rate frame_rate

2023-10-03 14:04 UTC, VincentJousse commented on src/lib.rs
> +  }
return a `&Fraction` and thus, just use &self.fraction

2023-10-03 14:04 UTC, VincentJousse commented on src/lib.rs
> +use Fraction::MilliSeconds;
Remove these lines from imports

2023-10-03 15:20 UTC, VincentJousse requested changes

2023-10-03 15:20 UTC, VincentJousse commented on tests/parser.rs
> +use frame_rate::FrameRate::_25_00;
Import only frame_rate::FrameRate

2023-10-04 07:33 UTC, valnoel commented on src/lib.rs
> +        frames, drop_frame, ..
Test

2023-10-04 13:50 UTC, VincentJousse requested changes

2023-10-04 13:50 UTC, VincentJousse commented on src/frame.rs
> +#[derive(Debug, Deserialize, Clone, PartialEq, Serialize)]
Jump a line after imports

2023-10-04 13:50 UTC, VincentJousse commented on src/frame.rs
> +pub struct Frame {
Rename struct Frame with TimecodeFrames
Rename file timecode_frames

2023-10-04 13:50 UTC, VincentJousse commented on src/frame.rs
> +  frames: u8,
Rename number_of_frames

2023-10-04 13:50 UTC, VincentJousse commented on src/frame.rs
> +  }
Jump lines between functions

2023-10-04 13:50 UTC, VincentJousse commented on src/fraction.rs
> +        format!("{}{:02}", separator, frame.frames())
Move this in frame.rs in :
```
impl ToString for Frame {
  fn to_string(&self) -> String {
  }
}
```

2023-10-05 08:37 UTC, VincentJousse requested changes

2023-10-05 08:42 UTC, VincentJousse requested changes

2023-10-05 08:42 UTC, VincentJousse commented on src/fraction.rs
> +      Fraction::Frame(..) => self.to_string(),
```suggestion
      Fraction::Frames(timecode_frames) => timecode_frames.to_string(),
```

2023-10-05 09:02 UTC, VincentJousse requested changes

2023-10-05 09:02 UTC, VincentJousse commented on src/fraction.rs
> +#[derive(Debug, Deserialize, Clone, PartialEq, Serialize)]
Jump a line

2023-10-05 10:11 UTC, VincentJousse requested changes

2023-10-05 10:11 UTC, VincentJousse commented on src/fraction.rs
> +      Fraction::Frames(timecode_frame) => timecode_frame.to_string(),
Use Self::

2023-10-05 10:11 UTC, VincentJousse commented on src/fraction.rs
> +      Fraction::MilliSeconds(milliseconds) => format!(".{:03}", milliseconds),
Use Self::

2023-10-05 10:11 UTC, VincentJousse commented on src/lib.rs
> +    let fraction = Fraction::MilliSeconds(ms as u16);
```suggestion
    let fraction = Fraction::MilliSeconds(duration.subsec_millis() as u16);
```

2023-10-05 10:11 UTC, VincentJousse commented on src/lib.rs
> +
Move unitary tests in a test module
(See https://doc.rust-lang.org/book/ch11-01-writing-tests.html)

2023-10-05 10:11 UTC, VincentJousse commented on src/lib.rs
> +    let hours = remaining / 3600;
Make u8 conversion here

2023-10-05 10:11 UTC, VincentJousse commented on src/lib.rs
> +    let minutes = remaining / 60;
Make u8 conversion here

2023-10-05 10:11 UTC, VincentJousse commented on src/lib.rs
> +    let seconds = remaining % 60;
Make u8 conversion here

2023-10-09 09:10 UTC, merged